version: 2.1

jobs:
  run-tests:
    #machine: 
    #   image: ubuntu-2204:current
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: start the ArangoDB in the background
          background: true
          command: |
              ssh remote-docker \<<EOF
                      echo "more commands can be added here since we now have full access to this machine"
                      git clone https://github.com/CircleCI-Public/circleci-demo-docker
                      echo "can do more things here"
                      docker run -e ARANGO_ROOT_PASSWORD=test123 -p 8529:8529 -d arangodb
              EOF
      #- run: 
      #    name: allow container to start fully in the background
      #    command: sleep 25
      - run:
          name: Run a simple healthcheck to confirm db is working
          command: | 
            DB_URL="http://$DOCKER_MACHINE_NAME:8529/_db/_system/_admin/aardvark/index.html"
            HTTP_STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" $DB_URL)
            if [ "$HTTP_STATUS_CODE" -eq 200 ]; then
                  echo "DB is running..."
              else
                   echo "Something is wrong...DB is not running"
                   exit 1
            fi



workflows:
  main:
    jobs:
      - run-tests
