version: 2.1

jobs:
  run-tests:
    #machine: 
    #   image: ubuntu-2204:current
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: start the ArangoDB in the background
          background: true
          command: |
             echo "more commands can be added here since we now have full access to this machine"
             git clone https://github.com/CircleCI-Public/circleci-demo-docker
             echo "can do more things here"
             docker run -e ARANGO_ROOT_PASSWORD=test123 -p 8529:8529 -d arangodb
      - run: 
          name: allow container to start fully in the background
          command: sleep 25
      - run:
          name: Run a simple healthcheck to confirm db is working
          command: | 
              url="http://127.0.0.1:8529/_db/_system/_admin/aardvark/index.html"
              response_code=$(curl -s -o /dev/null -w "%{http_code}" $url)
              if [ "$response_code" -eq 200 ]; then
                  echo "URL $url returned a 200 OK status code."
              else
                  echo "URL $url returned a non-200 status code: $response_code"
              fi



workflows:
  main:
    jobs:
      - run-tests
