version: 2.1

jobs:
  run-tests:
    resource_class: small
    parameters:
      python-version:
        type: string
        default: "latest"
      arangodb-version:
        type: string
        default: "arangodb:latest"
      arangodb-config:
        type: string
        default: "single.conf"
    docker:
      - image: python:<< parameters.python-version >>
        name: driver
      - image: arangodb/arangodb:latest
        name: db
        command: |
           echo "hello"
           curl https://google.com
    steps:
      - checkout
      #- setup_remote_docker:
      #     version: 20.10.18
      #- run: |
      #     ssh remote-docker \<<EOF
      #         sudo ufw allow 8529
      #        sudo docker run -e ARANGO_ROOT_PASSWORD=mypwd -p 8529:8529 -d --name arangodb-instance arangodb/arangodb
      #     EOF
      - run: nc -vz localhost 8529


workflows:
  test-single-python-3.10-community-3.10:
    jobs:
      - run-tests:
          python-version: "3.10.6"
          arangodb-version: "arangodb:3.10.9" # "arangodb/arangodb:3.10.10"
          arangodb-config: "single.conf"
