version: 2.1

jobs:
  run-tests:
    resource_class: small
    parameters:
      python-version:
        type: string
        default: "latest"
      arangodb-version:
        type: string
        default: "arangodb:latest"
      arangodb-config:
        type: string
        default: "single.conf"
    docker:
      - image: python:<< parameters.python-version >>
        name: driver
    steps:
      - checkout
      - setup_remote_docker:
           version: 20.10.18
      - run: |
           ssh remote-docker \<<EOF
               sudo ufw allow 8529
               sudo docker run -e ARANGO_ROOT_PASSWORD=mypwd -p 8529:8529 -d --name arangodb-instance arangodb/arangodb
           EOF
      - run:
          name: install dockerize # This is a utility that will attempt to connect to a database, in place of an application for this sample.
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db # If no database is found in 1 minute the job will fail.
          command: dockerize -wait tcp://localhost:8529 -timeout 1m


workflows:
  test-single-python-3.10-community-3.10:
    jobs:
      - run-tests:
          python-version: "3.10.6"
          arangodb-version: "arangodb:3.10.9" # "arangodb/arangodb:3.10.10"
          arangodb-config: "single.conf"
