version: 2.1

jobs:
  run-tests:
    #machine: 
    #   image: ubuntu-2204:current
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: start the ArangoDB in the remote-docker host
          command: |
             echo "more commands can be added here since we now have full access to this machine"
             git clone https://github.com/CircleCI-Public/circleci-demo-docker
             echo "can do more things here"
             docker run -e ARANGO_ROOT_PASSWORD=test123 -p 8529:8529 -d arangodb
             DB_URL="http://127.0.0.1:8529/_db/_system/_admin/aardvark/index.html"
             curl $DOCKER_HOST
             curl $DOCKER_MACHINE_NAME
      - run:
          name: do normal things within the container...
          command: jq --version     



workflows:
  main:
    jobs:
      - run-tests
